default:
  adapter: mysql2
  database: lyrical
  username: admin
  password: password
  host: localhost
development:
  adapter: mysql2
  database: lyrical
  username: admin
  password: password
  host: localhost
production:
  adapter: mysql2
  database: lyrical
  username: admin
  password: password
  host: localhost